[default_apps]
teams = "teams-for-linux --enable-features=UseOzonePlatform --ozone-platform=wayland --url {meeting_url}"
calendar_client = "thunderbird"
terminal = "kitty"
browser = "/opt/zen-browser-bin/zen-bin %u"

[units]
lengths = "meters"
weights = "kg"
volumes = "l"
temperatures = "C"
currency = "inr"

[debug]
try_suppress_errors = false
try_suppress_warnings = false
app_paths = []

[appearance]
width = 500
height = 450
gsk_renderer = "cairo"
icon_paths = ["~/.config/sherlock/icons"]
icon_size = 22
use_base_css = true
opacity = 1.0
mod_key_ascii = ["⇧", "⇧", "", "", "⎇", "✦", "✦", ""]

[behavior]
use_xdg_data_dir_icons = false
animate = false

[binds]
up = "control-k"
down = "control-j"
left = "control-ih"
right = "control-l"
context = "control-i"
modifier = "control"
exec_inplace = "control-return"

[files]
config = "/home/l0n3/.config/sherlock/config.toml"
css = "/home/l0n3/.config/sherlock/main.css"
fallback = "/home/l0n3/.config/sherlock/fallback.json"
alias = "/home/l0n3/.config/sherlock/sherlock_alias.json"
ignore = "/home/l0n3/.config/sherlock/sherlockignore"
actions = "/home/l0n3/.config/sherlock/sherlock_actions.json"

[runtime]
multi = false
center = false
photo_mode = false
display_raw = false
daemonize = false

[caching]
enable = true
cache = "/home/l0n3/.cache/sherlock/sherlock_desktop_cache.json"

[expand]
enable = false
edge = "top"
margin = 0

[backdrop]
enable = false
opacity = 0.6
edge = "top"

[status_bar]
enable = false

[search_bar_icon]
enable = false
